#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Dec 31 13:11:00 2022

@author: ana
"""

import pandas as pd
import numpy as np

IdEc = pd.read_csv('../dataset/IdEc.csv', header=0, index_col='ID')

with open('../data_ID.txt') as handle:
    IDs = [line.strip().split('.')[0] for line in handle.readlines()]

IdEc = IdEc.loc[~IdEc.index.isin(IDs)]

new_test_idx = np.random.choice(IdEc.index, size=5000, replace=False)
np.savetxt('../new_test_idx.txt', new_test_idx, fmt='%s')